### PR TITLE
feat: configurable callback port

### LINKED ISSUE #27: Make the listen port configurable
### Describe the problem you'd like to have solved

>Port `8080` is over used, and only having the `k8s-pixy-auth` binary listen on that could interfere with local development.

### Describe the ideal solution

>  A subcommand for `auth` to specify the listen port would be very useful. 

## Alternatives and current work-arounds

> maintain a fork.

### PR DESCRIPTION
**Pull request by v0lkc**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Makes the callback port configurable.

### References

Fixes #27 

### Testing

- [x] This change adds test coverage for new/changed/fixed functionality

- select a port (e.g. `1337`)
- make sure the redirect url is correctly configured in the IDP (for our example it must be `http://127.0.0.1:1337/callback`)
- pass the selected port to k8s-pixy-auth using the parameter `--port` 

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by v0lkc** [comment]
@grounded042 Kindly ask you for a review

**Review by grounded042 — APPROVED** [review]
Nice work @v0lkc! Thanks for the contribution.

**Comment by v0lkc** [comment]
@grounded042  Are you going to release a new version too? :)

**Comment by grounded042** [comment]
@v0lkc working on it - apparently TravisCI migrated sites and this project is not on the new site.

**Comment by grounded042** [comment]
@v0lkc here we go: https://github.com/auth0/k8s-pixy-auth/releases/tag/v0.4.0

**Pull request merged**
